name: Build and publish Docker image from merge-to-nontested branch
on:
  push:
    branches: [ merge-to-nontested ]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1.1.0
        with:
          tags: merge-to-nontested, bug
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: anodev/image-background-remove-tool
          tag_with_ref: true