name: "Docker images"

on:
  release:
    types: [ published ]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: {context}/Dockerfile.cpu
          tags: |
            anodev/carvekit:latest-cpu
            anodev/carvekit:${{ env-release_version }}-cpu
      -
        name: Build and push cuda
        uses: docker/build-push-action@v3
        with:
          push: true
          file: {context}/Dockerfile.cuda
          tags: |
            anodev/carvekit:latest-cuda
            anodev/carvekit:${{ env-release_version }}-cuda